require 'rest-client'

class Sender
  def initialize url
    @url = url
  end

  def send_package
    #generate_random_package
    generate_smart_package
    return unless @package

    RestClient.post @url, @package.to_json, {:content_type => :json, :accept => :json} {}
  end

  private

  def generate_waypoints
    @waypoints = [
      {
        point_index: 0,
        title: 'Start',
        description: 'Start point, generated by emulator',
        country: 'Ukraine',
        city: 'Chernigov',
        state: 'Chernigovskaya',
        street: 'Rocossovskogo',
        iso_code: 'UA',
        postal_code: '14032'
      },
      {
        point_index: @track_points.count - 1,
        title: 'Finish',
        description: 'Finish point, generated by emulator',
        country: 'Ukraine',
        city: 'Chernigov',
        state: 'Chernigovskaya',
        street: 'Rocossovskogo',
        iso_code: 'UA',
        postal_code: '14032'
      }
    ]
  end

  def generate_random_track_points count
    @track_points = []
    count.times { @track_points << get_random_track_point }
  end

  def generate_smart_track_points count
    @track_points = []
    point = get_random_track_point
    count.times do
      @track_points << point
      time_delta = rand 60..180
      alt_delta = rand -10..10
      lng_delta = rand -0.0001 + rand() * 0.005
      lat_delta = rand -0.0001 + rand() * 0.005
      speed_delta = rand -5..5
      point = [
        point[0] + time_delta,
        point[1] + lat_delta,
        point[2] + lng_delta,
        point[3] + alt_delta,
        point[4] + speed_delta
      ]
      @track_points << point
    end
  end

  def generate_random_package
    track_points_count = rand 100..1000
    generate_random_track_points track_points_count
    generate_waypoints

    @package = {
      track: {
        title: "Random track",
        description: "",
        device: "Emulator",
        points: @track_points,
        waypoints: @waypoints,
        private: rand(0..1) == 0
      }
    }
  end

  def generate_smart_package
    track_points_count = rand 10..50
    generate_smart_track_points track_points_count
    generate_waypoints

    @package = {
      track: {
        title: "Smart generated track",
        description: "",
        device: "Emulator",
        points: @track_points,
        waypoints: @waypoints,
        private: rand(0..1) == 0
      }
    }
  end

  def get_random_track_point
    [
      Time.new,
      rand(-90..89) + rand, # latitude
      rand(-180..179) + rand, # longtitude
      rand(50..149) + rand, # altitude
      rand(0..10) # speed
    ]
  end
end
